# Generated by Django 4.1.5 on 2023-02-13 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
