# Generated by Django 4.1.5 on 2023-01-18 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New User', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentedat',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 16, 3, 19, 117628)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
