# Generated by Django 4.1.5 on 2023-02-22 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 23, 30, 58, 284636)),
        ),
    ]
