# Generated by Django 4.1.5 on 2023-01-23 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_profile_name_alter_comment_commentedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProfile',
            fields=[
                ('name', models.CharField(default='New User', max_length=20, verbose_name='Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True)),
                ('pfp', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentedat',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 13, 37, 16, 77901)),
        ),
    ]
