# Generated by Django 4.1.5 on 2023-02-22 04:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 23, 33, 57, 963019)),
        ),
    ]
