# Generated by Django 4.1.5 on 2023-01-23 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newprofile_alter_comment_commentedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentedat',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 14, 29, 10, 209173)),
        ),
        migrations.AlterField(
            model_name='newprofile',
            name='pfp',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
