# Generated by Django 4.1.5 on 2023-02-22 04:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_profileid_alter_post_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 23, 39, 1, 981672)),
        ),
    ]
