# Generated by Django 4.1.5 on 2023-02-13 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_newprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 12, 54, 22, 93626)),
        ),
    ]
