# Generated by Django 4.1.5 on 2023-02-25 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newprofile_id_alter_post_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 13, 23, 57, 153420)),
        ),
    ]
