# Generated by Django 4.1.5 on 2023-02-16 20:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 15, 38, 22, 896407)),
        ),
    ]
