# Generated by Django 4.1.5 on 2023-02-25 18:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 13, 24, 47, 445542)),
        ),
    ]
